language: php
sudo: enabled
php:
  - 7.2
node_js:
  - 8.11
services:
  - mysql
  - mongodb
before_install:
  - chmod +x install-dependencies.sh
install: ./install-dependencies.sh
script: ./vendor/bin/phpunit --bootstrap vendor/autoload.php --debug --colors=always